name: CI

on:
  pull_request:
    branches: [ develop, main, master ]
  push:
    branches: [ develop, main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./dailyq/gradlew
      
    - name: Clean and Build with Gradle
      run: |
        cd dailyq
        ./gradlew clean build -x test --no-daemon --stacktrace
        
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: build-libs
        path: dailyq/build/libs/*.jar

